export interface Config {
    minDate: Date,
    maxDate: Date,
    svgWidth: number,
    svgHeight: number,
    rowHeight: number,
    barHeight: number,
    headerHeight: number,
    viewModeSliderHeight: number,
    zoomSliderHeight: number,
    labelsWidth: number,
    scrollBarThickness: number,
    chartWidth: number,
    chartHeight: number,
    supportedLevels: number[],
    minUnitWidth: number,
    spaceBetweenGroups: number,
    minPadding: number,
    maxLabelsWidthPercentage: number,
    defaultBarColor: string,
    showOverdue: boolean,
    showWeekend: boolean,
    onScaleClick(x: number, y: number): void;
}

export let config: Config = {
    minDate: null,
    maxDate: null,
    svgWidth: 1200,
    svgHeight: 800,
    rowHeight: 32,
    barHeight: 23,
    labelsWidth: 0,
    headerHeight: 70,
    viewModeSliderHeight: 40,
    zoomSliderHeight: 40,
    scrollBarThickness: 8,
    chartWidth: 500,
    chartHeight: 500,
    supportedLevels: [0, 1, 2, 3, 4],
    minUnitWidth: 25,
    spaceBetweenGroups: 24,
    minPadding: 8, 
    maxLabelsWidthPercentage: 0.2,
    defaultBarColor: "#a0a0a0", 
    onScaleClick: null,
    showOverdue: false,
    showWeekend: false
};